name: Entelligence AI Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Entelligence AI PR Review
        uses: ShifanaRajamohamed/pr-review-action@main
