name: Entelligence AI Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Entelligence AI Review
        uses: entelligenceai/pr-review-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
